from pydoc import plain


ciphertext = "ROYHRZBOPEZCGOEZGOMGOKGRUGCUIQRUBBXOFFUUPCYUPCZIUWOMGUFOPEGROHZWZCHOKWIAERGKBOYZIHUPCGROHZXOOBKOMPGUAPHXOFFUWMGHRZXOMBCPOGZVZPEZGRZIRZUCGRIOMERGRZCOOIYULUPCZVZPAKFLRZUCYOMBCEOGRIOMERXOFFUGROMERGNOOIUBAXZXOFFUAGYOMBCWZOKVZILBAGGBZMHZYAGROMGFLHROMBCZIHCOGORXOFFUROYAYAHRAXOMBCHRMGMNBAQZUGZBZHXONZAGRAPQAXOMBCXOFFUAKAOPBLQPOYROYGOWZEAPCOGKOIXOFFULOMHZZXOFFUHOFUPLOMGOKGRZYULGRAPEHRUCRUNNZPZCBUGZBLXOFFUGRUGUBAXZRUCWZEMPGOGRAPQGRUGVZILKZYGRAPEHAPCZZCYZIZIZUBBLAFNOHHAWBZ"

for key in range(25):
    plaintext = []
    for x in ciphertext:
        plaintext.append(chr( (((ord(x) - ord('A')) + key ) % 26) + ord('A')) )
    print(''.join(plaintext) + "\n")
 